# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2323460a737716eb2600d8e5cc35106de3ea2df0ef1103b54a0eff62f76cf7561365033db1f939335a23dd977da124c8ebedf4214064add2c49df1940a01bb39

test:
  secret_key_base: f0eed8651487ea6f0543417992d7eab901f3f7ca83678bd24a07f6f6333c03eb93377771a79521bf0900741cbb5c4205093e62d59ec1085229199d637aff5cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
